version: '3'

services:
  backend:
    container_name: rentalx-app
    build: 
      context: .devcontainer/
    environment:
      TEST_DB_NAME: ${DB_NAME}-test
    command: sleep infinity
    volumes:
      - .:/workspace:cached

  database:
    environment: 
      TEST_DB_NAME: ${DB_NAME}-test
    volumes:
      - .devcontainer/pg-init-scripts:/docker-entrypoint-initdb.d
