version: '3'

services:
  app:
    container_name: rentalx-app
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 14
        USER_UID: 1000
        USER_GID: 1000
    env_file: .env
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    networks:
      - rentalx

  database:
    container_name: rentalx-db
    image: postgres:13.2
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - rentalx

  redis:
    container_name: rentalx-redis
    image: redis:6.0.14-alpine
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/bitnami/redis/data
    networks:
      - rentalx

volumes:
  postgres-data:
  redis-data:

networks:
  rentalx:
    